import { type Worker, Availability } from "./types";

export const mockWorkers: Worker[] = [
  {
    id: "1",
    name: "John Doe",
    trade: "Plumber",
    location: "New York, NY",
    rating: 4.8,
    reviews: 125,
    availability: Availability.AVAILABLE_NOW,
    imageUrl: "https://picsum.photos/seed/johndoe/200/200",
    bio: "Licensed plumber with over 10 years of experience in residential and commercial plumbing. Fast, reliable, and affordable.",
  },
  {
    id: "2",
    name: "Jane Smith",
    trade: "Electrician",
    location: "Brooklyn, NY",
    rating: 4.9,
    reviews: 210,
    availability: Availability.WEEKDAYS,
    imageUrl: "https://picsum.photos/seed/janesmith/200/200",
    bio: "Certified electrician specializing in smart home installations and electrical repairs. Safety is my top priority.",
  },
  {
    id: "3",
    name: "Mike Johnson",
    trade: "Carpenter",
    location: "Queens, NY",
    rating: 4.7,
    reviews: 88,
    availability: Availability.WEEKENDS,
    imageUrl: "https://picsum.photos/seed/mikejohnson/200/200",
    bio: "Skilled carpenter with a passion for custom furniture and cabinetry. No job is too big or too small.",
  },
  {
    id: "4",
    name: "Emily Williams",
    trade: "Painter",
    location: "New York, NY",
    rating: 5.0,
    reviews: 150,
    availability: Availability.NEXT_WEEK,
    imageUrl: "https://picsum.photos/seed/emilywilliams/200/200",
    bio: "Professional painter delivering high-quality interior and exterior paint jobs. Meticulous and clean work guaranteed.",
  },
  {
    id: "5",
    name: "David Brown",
    trade: "Landscaper",
    location: "Bronx, NY",
    rating: 4.6,
    reviews: 75,
    availability: Availability.AVAILABLE_NOW,
    imageUrl: "https://picsum.photos/seed/davidbrown/200/200",
    bio: "Expert landscaper creating beautiful and sustainable outdoor spaces. Services include design, maintenance, and hardscaping.",
  },
  {
    id: "6",
    name: "Sarah Miller",
    trade: "HVAC Technician",
    location: "Staten Island, NY",
    rating: 4.8,
    reviews: 95,
    availability: Availability.WEEKDAYS,
    imageUrl: "https://picsum.photos/seed/sarahmiller/200/200",
    bio: "Certified HVAC technician for all your heating, ventilation, and air conditioning needs. 24/7 emergency service available.",
  },
  {
    id: "7",
    name: "Chris Garcia",
    trade: "Roofer",
    location: "Brooklyn, NY",
    rating: 4.5,
    reviews: 60,
    availability: Availability.NEXT_WEEK,
    imageUrl: "https://picsum.photos/seed/chrisgarcia/200/200",
    bio: "Experienced roofer specializing in repairs, replacements, and inspections. Using only the best materials for a long-lasting roof.",
  },
  {
    id: "8",
    name: "Jessica Rodriguez",
    trade: "General Contractor",
    location: "New York, NY",
    rating: 4.9,
    reviews: 180,
    availability: Availability.WEEKENDS,
    imageUrl: "https://picsum.photos/seed/jessicarodriguez/200/200",
    bio: "Your trusted partner for home renovations and remodeling projects. From concept to completion, I manage it all.",
  },
];
